Corrected Pipelines

diff --git a/.github/workflows/terraform-multi-stage.yml b/.github/workflows/terraform-multi-stage.yml
--- a/.github/workflows/terraform-multi-stage.yml
+++ b/.github/workflows/terraform-multi-stage.yml
@@ -1,6 +1,11 @@
 name: Terraform Apply
 on:
   workflow_dispatch:
+    inputs:
+      RG:
+        description: 'The resource group to work with.'
+        required: true
+
 jobs:
   plan:
     runs-on: ubuntu-latest
@@ -12,46 +17,49 @@ jobs:
       BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
       BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
       BACKEND_STORAGE_CONTAINER_NAME: ${{ secrets.BACKEND_STORAGE_CONTAINER_NAME }}
+
     steps:
+
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v2
 
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set environment variables and construct TF_BACKEND_KEY
-        working-directory: src/terraform
+      - name: Path Checker
+        working-directory: "src/terraform"
         run: |
-          ApplicationName=$(grep '^ApplicationName =' backend.tfvars | sed 's/ApplicationName = "\(.*\)"/\1/')
-          EnvironmentName=$(grep '^EnvironmentName =' backend.tfvars | sed 's/EnvironmentName = "\(.*\)"/\1/')
-          echo "ApplicationName=${ApplicationName}" >> $GITHUB_ENV
-          echo "EnvironmentName=${EnvironmentName}" >> $GITHUB_ENV
-          TF_BACKEND_KEY="${ApplicationName}-${EnvironmentName}.tfplan"
-          echo "TF_BACKEND_KEY=${TF_BACKEND_KEY}" >> $GITHUB_ENV
-        shell: bash
+          if [ ! -f "${{ github.event.inputs.RG }}.tfplan" ]; then
+            echo "Terraform plan file not found. Ensure RG name is correct and RG directory is initialized with all required code."
+            exit 1
+          fi
+      
+      - name: Set Plan File Name
+        working-directory: "src/terraform"
+        run: |
+          echo "TF_BACKEND_KEY=${{ github.event.inputs.RG }}.tfplan" >> $GITHUB_ENV
 
       - name: Terraform Validate
         working-directory: src/terraform
         run: |
-          chmod +x ../../.github/workflows/scripts/terraform-with-backend.sh
-          ../../.github/workflows/scripts/terraform-with-backend.sh validate
+          chmod +x ../../../.github/workflows/scripts/terraform-with-backend.sh
+          ../../../.github/workflows/scripts/terraform-with-backend.sh validate
 
       - name: Terraform Plan
-        working-directory: src/terraform
+        working-directory: "src/terraform/${{ github.event.inputs.RG }}"
         run: |
-          chmod +x ../../.github/workflows/scripts/terraform-with-backend.sh
-          ../../.github/workflows/scripts/terraform-with-backend.sh plan -var-file=backend.tfvars -out=${{ env.TF_BACKEND_KEY }}
+          chmod +x ../../../.github/workflows/scripts/terraform-with-backend.sh
+          ../../../.github/workflows/scripts/terraform-with-backend.sh plan -var-file=backend.tfvars -out="${{ github.event.inputs.RG }}.tfplan"
 
 
       - name: Upload Terraform Plan as Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: tfplan
-          path: src/terraform/${{ env.TF_BACKEND_KEY }}
+          name: "${{ github.event.inputs.RG }}.tfplan"
+          path: "src/terraform/${{ github.event.inputs.RG }}.tfplan"
 
   apply:
-    environment : production
-    needs : plan
+    needs: plan
     runs-on: ubuntu-latest
     env:
       ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
@@ -68,32 +76,26 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set environment variables and construct TF_BACKEND_KEY
-        working-directory: src/terraform
+      - name: Set Plan File Name
+        working-directory: "src/terraform"
         run: |
-          ApplicationName=$(grep '^ApplicationName =' backend.tfvars | sed 's/ApplicationName = "\(.*\)"/\1/')
-          EnvironmentName=$(grep '^EnvironmentName =' backend.tfvars | sed 's/EnvironmentName = "\(.*\)"/\1/')
-          echo "ApplicationName=${ApplicationName}" >> $GITHUB_ENV
-          echo "EnvironmentName=${EnvironmentName}" >> $GITHUB_ENV
-          TF_BACKEND_KEY="${ApplicationName}-${EnvironmentName}.tfplan"
-          echo "TF_BACKEND_KEY=${TF_BACKEND_KEY}" >> $GITHUB_ENV
-        shell: bash
+          echo "TF_BACKEND_KEY=${{ github.event.inputs.RG }}.tfplan" >> $GITHUB_ENV
 
       - name: Download artifact
         uses: actions/download-artifact@v4
         with:
-          name: tfplan
-          path: src/terraform
+          name: "${{ github.event.inputs.RG }}.tfplan"
+          path: "src/terraform/${{ github.event.inputs.RG }}.tfplan"
 
       - name: Terraform Validate
-        working-directory: src/terraform
+        working-directory: "src/terraform/${{ github.event.inputs.RG }}"
         run: |
-          chmod +x ../../.github/workflows/scripts/terraform-with-backend.sh
-          ../../.github/workflows/scripts/terraform-with-backend.sh validate
+          chmod +x ../../../.github/workflows/scripts/terraform-with-backend.sh
+          ../../../.github/workflows/scripts/terraform-with-backend.sh validate
 
       - name: Terraform Apply
-        working-directory: src/terraform
+        working-directory: "src/terraform/${{ github.event.inputs.RG }}"
         run: |
-          chmod +x ../../.github/workflows/scripts/terraform-with-backend.sh
-          ../../.github/workflows/scripts/terraform-with-backend.sh apply -auto-approve "${{ env.TF_BACKEND_KEY }}"
+          chmod +x ../../../.github/workflows/scripts/terraform-with-backend.sh
+          ../../../.github/workflows/scripts/terraform-with-backend.sh apply -auto-approve "${{ github.event.inputs.RG }}.tfplan"
 
